### PR TITLE
Add GitLab icon and URL

### PR DESCRIPTION
**Pull request by fnuttens**
It’s me again 🙂

Here's a new PR that adds a GitLab placeholder.

### CODE REVIEW

**Comment by mintyfrankie** [comment]
Thanks for the idea!

I was actually thinking about refactoring this function to maybe add a `custom` key to `personalInfo`, so users can customise an icon by using an array of `(someIcon, someValue)`. So if one wants gitlab, they can add a k-y pair of `custom: (fa-gitlab, mintyfrankie)`.

Don't know how we can make it URL though.

Feel free to tell me what you think, or if you want to patch a new commit!

**Comment by fnuttens** [comment]
Hey! The idea crossed my mind too but I think it might be overkill for the problem it solves. I would actually benefit from it because I primarily use a different GitLab instance from the main one (hence my personal patch that landed on the previous PR by mistake), but I still think it's a niche requirement as most people put the same links on their resume.

I like the current metadata file for its simplicity, and I feel like this feature might harm it: I would have to pay attention to the order of the values in the array, read the doc of the template to understand that fontawesome icons are supported and go there myself to find the relevant ones.

**Comment by mintyfrankie** [comment]
Indeed, I was weighing that too. 

On the other side, I've got most of the Issues / PRs around the `headerIcon` (see #1 #5 #6 and yours #8), and I have the impression that people request a lot more customisations about this matter.

In your opinion, is there viable to keep like basic k-v pairs (like phone, email, etc) while adding a new condition catch for the `custom` key, and read through the `value`? something like:

```
if k == "custom" {v.at[0]...link(v.at[1]...)}
```

I can patch a new commit upon this PR if you'd like.

**Comment by mintyfrankie** [comment]
Hi @fnuttens I am merging your PR first, given that no ideal solution can be properly established for now. Thanks for the contribution！

**Comment by fnuttens** [comment]
Thanks for merging!

> In your opinion, is it viable to keep like basic k-v pairs (like phone, email, etc) while adding a new condition catch for the custom key, and read through the value?

Yes for sure it's a good idea to keep the simple stuff simple while adding a custom key 🙂

**Pull request merged**
