### PR TITLE
fix mobile icon instead of the current id-badge icon

### PR DESCRIPTION
**Pull request by munzirtaha**

### CODE REVIEW

**Comment by mintyfrankie** [comment]
Hi @munzirtaha thanks for the PR. 

It makes sense that the icon should be mobile icon. But on my local environment I cannot get `\u{f10b}` rendered correctly, even with the `--font-path` directive well set. Can you see if this can work on other environments?

**Comment by munzirtaha** [comment]
Ah. Just checked the Font Awesome you are bundling and \u{f10b} is not available there. It's available on their Pro version as can be verified at https://fontawesome.com/icons/mobile-button. It worked on my system because of the fallback mechanism and I already have Symbols Nerd font installed.

Any specific reason why you are not bundling the Nerd Symbols Only font (https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/NerdFontsSymbolsOnly.zip) instead of Font Awesome which contains much more symbols and free?

Another option is to use the unicode symbol \u{1f4f1} (📱) or #emoji.phone which is available in noto emoji, does this make sense to you?

**Comment by mintyfrankie** [comment]
> Ah. Just checked the Font Awesome you are bundling and `\u{f10b}` is not available there. It's available on their Pro version as can be verified at https://fontawesome.com/icons/mobile-button. It worked on my system because of the fallback mechanism and I already have Symbols Nerd font installed.
> 
> Any specific reason why you are not bundling the [Nerd Symbols Only](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/NerdFontsSymbolsOnly.zip) font instead of Font Awesome which contains much more symbols and free?
> 
> Another option is to use the unicode symbol `\u{1f4f1}` (`📱`) or #emoji.phone which is available in noto emoji, does this make sense to you?

Yep I've tested the `Symbols Nerd Font` but unfortunately it didn't work neither, either with `--font-path` or with system fallback (`Symbols Nerd Font` is clearly listed by `typest fonts` in either case); however on the web app `\u{f10b}` does work. So either it has something to do with typst-cli, or it's a MacOS issue. 

I think for the time being let's stick with this non-optimal solution and I will merge this PR once the font issue fixed. Otherwise if you come up with any other solution I'd love to test it out!

**Comment by munzirtaha** [comment]
Mostly a MacOS issue because I am using typst-cli in Arch Linux and `\u{f10b}` works properly in both the regular and mono.

What about the `\u{1f4f1}` solution?

The only remaining suggestion I have is trash the Mac system, use Linux and let Mac users solve their own issues ;)

Thanks for your great work. I just trashed my LibreOffice resume and replaced it with AwesomeCV-Typst

**Comment by mintyfrankie** [comment]
> What about the `\u{1f4f1}` solution?

I've tested this too but it didn't work. Might be related to the Emoji rendering issue [#144](https://github.com/typst/typst/issues/144) here. 

While I think leaving MacOS users in hell is not the ultimate solution :), fingers crossed that later versions of Typst will get this fixed. I will leave this PR open and merge it when the time comes.

Thanks for the contribution and stay tuned!

**Comment by munzirtaha** [comment]
That issue is about Noto Color Emoji, but you can use the black and white version of instead. It's available at https://fonts.google.com/noto/specimen/Noto+Emoji

I tested both the static and variable fonts and both works.

**Comment by mintyfrankie** [comment]
Hi @munzirtaha, a quick update about the issue you have brought up: I somehow managed to get the mobile icon worked with the new Typst package included in the latest Typst update, though I did wonder why 🤷

Feel free to check if that works for you too! While I am closing this PR, I'd be happy to discuss any new contribution!

**Pull request closed without merging**
